train_params:
  grad-scaler: false
  loss: hinton
  loss-params:
    hard-mining: false
    reduction: mean
    pos-weight: 1.5
  lr: 0.001
  temperature: 2.0
  loss-weight: 0.7
  penultimate-weight: 0.3
  penultimate-layer: collision.fc2
  intermediate-weights: [0.25, 0.25, 0.25, 0.25]
  intermediate-layers: [backbone.layer1,  backbone.layer2,  backbone.layer3,  backbone.layer4]
session_params:
  classes: 2
  model: resnet18
  teacher-model: base-model/ResNetHinton_final.pth
  pruning-params:
    ignored-layers: [collision]
    num-batches: 2
    steps: 5
    pruning-ratio: 0.85
    is-taylor: true
  batch-size: 64
  n_workers: 4
  epochs: 10
  target-class: 1
  decision-threshold: 0.5
  checkpoint-history: 20
  save-frequency: 200
  checkpoint-dir: out-pruning-taylor
  log-path: logs-pruning-taylor
  state-save: false
  data-root: f:/dev/datasets/collision_dataset
  eval-metric: recall
  input-size: !!python/tuple
    - 224
    - 224
  mean: !!python/tuple
    - 0.485
    - 0.456
    - 0.406
  std: !!python/tuple
    - 0.229
    - 0.224
    - 0.225
