train_params:
  grad-scaler: false
  loss: hinton
  loss-params:
    hard-mining: false
    reduction: mean
    pos-weight: 1.5
  lr: 0.001
  temperature: 2.0
  loss-weight: 0.7
  penultimate-weight: 0.3
  penultimate-layer: collision.fc2
  intermediate-weights: [0.25, 0.25, 0.25, 0.25]
  intermediate-layers: []
session_params:
  classes: 2
  model: resnet18
  teacher-model: out-cp-oneshot/ResNetHinton_final.pth
  quantization-params:
    type: training-aware
    num-batches: 15
  batch-size: 64
  n_workers: 4
  epochs: 5
  target-class: 1
  decision-threshold: 0.5
  checkpoint-history: 20
  save-frequency: 200
  checkpoint-dir: out-quantization-cp
  log-path: logs-quantization-cp
  state-save: true
  data-root: f:/dev/datasets/collision_dataset
  eval-metric: recall
  input-size: !!python/tuple
    - 224
    - 224
  mean: !!python/tuple
    - 0.485
    - 0.456
    - 0.406
  std: !!python/tuple
    - 0.229
    - 0.224
    - 0.225
